title: "City Business Center Limassol Offices"
asset_tag: "20200617091500"
email: offices@cbcl.com.cy
popup_enabled: "no"
popup_title: "Sea View Vacancy"
popup_text: "Offices 6 & 8"
popup_info: "Call +357 25 874144"
