title: City Business Center Limassol Offices
email: offices@cbcl.com.cy
asset_tag: "20200617091500"
popup_enabled: true
popup_title: Sea View Vacancy
popup_text: Offices 6 & 8
popup_info: Call +357 25 874144
