backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow
media_folder: /assets/img

collections:
  - label: "Settings"
    name: "settings"
    files:
      - label: "Site Settings"
        name: "settings"
        file: "site/_data/settings.yml"
        fields:
          - {label: Email, name: email, widget: string}
          - {label: Asset Tag, name: asset_tag, widget: string}
          - {label: Popup enabled, name: popup_enabled, widget: string}
          - {label: Popup title, name: popup_title, widget: string}
          - {label: Popup text, name: popup_text, widget: string}
          - {label: Popup info, name: popup_info, widget: string}
